-- A centre's work is divided into school years, and until now nothing said so.
--
-- Two things followed from that. The pool was every teacher ever added to the
-- centre, for ever: somebody who moved to another school in July kept receiving
-- duties in September, and could not be taken out because removing a teacher
-- who has served destroys the turns he is owed. And cumulative fairness read
-- every session the centre had ever run, so 2027-2028 would have been balanced
-- against 2026-2027 and every year before it, for work nobody remembers.
--
-- A teacher's presence is all or nothing for a year — nobody leaves between the
-- régionale and the rattrapage — so membership of a year is the right unit. The
-- teacher row itself is never deleted: he keeps his matricule, his name and
-- everything he did, and simply stops being in the pool of the years after he
-- left.

create table school_year (
    id        bigint generated by default as identity primary key,
    center_id bigint      not null references center (id) on delete cascade,
    label     varchar(20) not null,
    constraint uq_school_year unique (center_id, label)
);

-- The years the sessions already entered imply. A session in June 2026 belongs
-- to 2025-2026; the year turns over in September, not in January.
insert into school_year (center_id, label)
select distinct o.center_id,
       case when extract(month from coalesce(o.starts_on, cast(o.created_at as date))) >= 9
            then cast(cast(extract(year from coalesce(o.starts_on, cast(o.created_at as date))) as int) as varchar)
                 || '-'
                 || cast(cast(extract(year from coalesce(o.starts_on, cast(o.created_at as date))) as int) + 1 as varchar)
            else cast(cast(extract(year from coalesce(o.starts_on, cast(o.created_at as date))) as int) - 1 as varchar)
                 || '-'
                 || cast(cast(extract(year from coalesce(o.starts_on, cast(o.created_at as date))) as int) as varchar)
       end
from operation o;

-- A centre whose rooms and pool are entered but which has no session yet still
-- needs a year to hold them.
insert into school_year (center_id, label)
select c.id,
       case when extract(month from current_date) >= 9
            then cast(cast(extract(year from current_date) as int) as varchar)
                 || '-' || cast(cast(extract(year from current_date) as int) + 1 as varchar)
            else cast(cast(extract(year from current_date) as int) - 1 as varchar)
                 || '-' || cast(cast(extract(year from current_date) as int) as varchar)
       end
from center c
where not exists (select 1 from school_year y where y.center_id = c.id);

alter table operation add column school_year_id bigint references school_year (id);

update operation o set school_year_id = (
    select y.id from school_year y
    where y.center_id = o.center_id
      and y.label =
          case when extract(month from coalesce(o.starts_on, cast(o.created_at as date))) >= 9
               then cast(cast(extract(year from coalesce(o.starts_on, cast(o.created_at as date))) as int) as varchar)
                    || '-'
                    || cast(cast(extract(year from coalesce(o.starts_on, cast(o.created_at as date))) as int) + 1 as varchar)
               else cast(cast(extract(year from coalesce(o.starts_on, cast(o.created_at as date))) as int) - 1 as varchar)
                    || '-'
                    || cast(cast(extract(year from coalesce(o.starts_on, cast(o.created_at as date))) as int) as varchar)
          end);

alter table operation alter column school_year_id set not null;

create table teacher_school_year (
    teacher_id     bigint not null references teacher (id) on delete cascade,
    school_year_id bigint not null references school_year (id) on delete cascade,
    primary key (teacher_id, school_year_id)
);

-- The pool was centre-wide, so the honest backfill is that everybody was in
-- every year of their centre. Nothing is known about who arrived when, and
-- inventing it would be worse than saying so.
insert into teacher_school_year (teacher_id, school_year_id)
select t.id, y.id from teacher t join school_year y on y.center_id = t.center_id;
