create table operation_file (
    id          bigint generated by default as identity primary key,
    name        varchar(200) not null,
    content     text         not null,
    uploaded_at timestamp    not null
);

create table solve_job (
    id                 bigint generated by default as identity primary key,
    operation_file_id  bigint      not null references operation_file (id),
    status             varchar(20) not null,
    time_limit_seconds int         not null,
    error              text,
    feasible           boolean,
    hard_violations    int,
    soft_violations    int,
    unfilled           int,
    result             text,
    created_at         timestamp   not null,
    started_at         timestamp,
    finished_at        timestamp
);
