-- Real center data, instead of keeping only the uploaded file.
-- Lets an operation be edited in the application, and lets the workload of
-- past operations be read from history rather than typed into a file.

create table center (
    id   bigint generated by default as identity primary key,
    name varchar(200) not null
);

create table room (
    id        bigint generated by default as identity primary key,
    center_id bigint       not null references center (id),
    reference varchar(50)  not null,
    label     varchar(200) not null,
    constraint uq_room_reference unique (center_id, reference)
);

create table teacher (
    id            bigint generated by default as identity primary key,
    center_id     bigint       not null references center (id),
    reference     varchar(50)  not null,
    -- numéro de matricule / رقم التأجير: the staff number the administration
    -- uses to identify a civil servant. Required, and the real identity of a
    -- teacher — names are ambiguous, matricules are not.
    matricule     varchar(50)  not null,
    name          varchar(200) not null,
    subject       varchar(100) not null,
    establishment varchar(200),
    gender        varchar(10),
    constraint uq_teacher_reference unique (center_id, reference),
    constraint uq_teacher_matricule unique (matricule)
);

create table teacher_unavailability (
    id            bigint generated by default as identity primary key,
    teacher_id    bigint not null references teacher (id) on delete cascade,
    unavailable_on date  not null,
    start_time    time,
    end_time      time
);

create table operation (
    id         bigint generated by default as identity primary key,
    center_id  bigint       not null references center (id),
    reference  varchar(100) not null,
    type       varchar(40)  not null,
    created_at timestamp    not null
);

create table exam_slot (
    id             bigint generated by default as identity primary key,
    operation_id   bigint      not null references operation (id) on delete cascade,
    reference      varchar(50) not null,
    slot_date      date        not null,
    start_time     time        not null,
    end_time       time        not null,
    ordinal_in_day int         not null,
    reserve_count  int         not null
);

create table exam (
    id                    bigint generated by default as identity primary key,
    slot_id               bigint       not null references exam_slot (id) on delete cascade,
    reference             varchar(50)  not null,
    subject               varchar(100) not null,
    stream                varchar(100) not null,
    surveillants_per_room int          not null,
    permanence_count      int          not null
);

create table exam_room (
    exam_id bigint not null references exam (id) on delete cascade,
    room_id bigint not null references room (id),
    primary key (exam_id, room_id)
);

-- a job now solves a stored operation; the uploaded file becomes optional history
alter table solve_job alter column operation_file_id drop not null;
alter table solve_job add column operation_id bigint references operation (id);

-- per-teacher duty counts of a finished job: the source of cumulative fairness
create table job_workload (
    id         bigint generated by default as identity primary key,
    job_id     bigint      not null references solve_job (id) on delete cascade,
    teacher_id bigint      not null references teacher (id),
    role       varchar(20) not null,
    duty_count int         not null,
    constraint uq_job_workload unique (job_id, teacher_id, role)
);
