-- The schedule becomes editable data instead of a stored document.
--
-- Each duty of a solved job gets a row, so an administrator can change who
-- holds it, pin it against the next solve, and have the workload ledger follow
-- what the schedule actually says. job_workload is dropped: the same numbers
-- are now derived from these rows, and two sources of truth is one too many.

create table assignment (
    id         bigint generated by default as identity primary key,
    job_id     bigint       not null references solve_job (id) on delete cascade,
    duty_id    varchar(160) not null,
    slot_ref   varchar(50)  not null,
    exam_ref   varchar(50),
    room_ref   varchar(50),
    role       varchar(20)  not null,
    teacher_id bigint references teacher (id),
    -- a pinned assignment survives the next solve untouched
    pinned     boolean      not null default false,
    constraint uq_assignment unique (job_id, duty_id)
);

create index idx_assignment_teacher on assignment (teacher_id);

drop table job_workload;
