-- A filière of one session, with the rooms it occupies for the whole session.
--
-- The rooms belong to the filière rather than to each épreuve: a centre gives
-- Lettres salle 1 and Sciences physiques salles 6 à 10 for the three days, and
-- restating that on every subject is how entering a timetable became an
-- afternoon's work. An exam still carries its own rooms — that is what the
-- solver reads — but they are filled from here.
--
-- Filières are declared per session, not per centre: 1BAC runs LSH / SM / SE
-- while 2BAC runs Lettres / Sciences Humaines / Sciences physiques, and a
-- stream may split in two from one year to the next.
create table operation_stream (
    id           bigint generated by default as identity primary key,
    operation_id bigint       not null references operation (id) on delete cascade,
    name         varchar(120) not null,
    ordinal      int          not null,
    constraint uq_operation_stream unique (operation_id, name)
);

create table operation_stream_room (
    stream_id bigint not null references operation_stream (id) on delete cascade,
    room_id   bigint not null references room (id),
    primary key (stream_id, room_id)
);
