-- What a centre teaches and which filières it runs.
--
-- These are properties of the centre, not of one session and not of whoever
-- happens to be in the teacher list: two centres in the same city run
-- different filières and examine different subjects, and the administrator has
-- to be able to correct the list rather than retype it into every form.
--
-- Names, not identifiers, are what teachers and épreuves store — the solver
-- matches a teacher's subject to an épreuve's by exact string. The catalogue
-- is therefore the source of the pickers, and renaming an entry rewrites the
-- rows that used it so the two can never drift apart.
create table center_subject (
    id        bigint generated by default as identity primary key,
    center_id bigint       not null references center (id) on delete cascade,
    name      varchar(120) not null,
    constraint uq_center_subject unique (center_id, name)
);

create table center_stream (
    id        bigint generated by default as identity primary key,
    center_id bigint       not null references center (id) on delete cascade,
    name      varchar(120) not null,
    constraint uq_center_stream unique (center_id, name)
);

-- Existing centres already hold both lists implicitly: in the subjects their
-- teachers teach, in the subjects their papers examine, and in the filières
-- their sessions declared. Seed from all three so nothing has to be re-entered.
insert into center_subject (center_id, name)
select distinct t.center_id, t.subject
from teacher t
where t.subject is not null;

insert into center_subject (center_id, name)
select distinct o.center_id, e.subject
from exam e
         join exam_slot s on e.slot_id = s.id
         join operation o on s.operation_id = o.id
where e.subject is not null
  and not exists (select 1
                  from center_subject cs
                  where cs.center_id = o.center_id
                    and cs.name = e.subject);

insert into center_stream (center_id, name)
select distinct o.center_id, os.name
from operation_stream os
         join operation o on os.operation_id = o.id;

insert into center_stream (center_id, name)
select distinct o.center_id, e.stream
from exam e
         join exam_slot s on e.slot_id = s.id
         join operation o on s.operation_id = o.id
where e.stream is not null
  and not exists (select 1
                  from center_stream cs
                  where cs.center_id = o.center_id
                    and cs.name = e.stream);
